import { Layers } from 'lucide-react'
import type { ReactNode } from 'react'
import {
  AWSIcon,
  BootstrapIcon,
  CloudflareIcon,
  CypressIcon,
  DockerIcon,
  FastifyIcon,
  FigmaIcon,
  FlaskIcon,
  FlutterIcon,
  GitHubIcon,
  GitIcon,
  GiteaIcon,
  GithubActionsIcon,
  GoIcon,
  JavascriptIcon,
  LinkedInIcon,
  NextIcon,
  NodeJSIcon,
  PrismaIcon,
  PythonIcon,
  ReactIcon,
  TailwindIcon,
  TraefikIcon,
  TypescriptIcon,
  ViteIcon,
  WhatsAppIcon,
  ZodIcon,
} from '.'

export const iconsNode: Record<string, ReactNode> = {
  aws: <AWSIcon />,
  bootstrap: <BootstrapIcon />,
  cloudflare: <CloudflareIcon />,
  cypress: <CypressIcon />,
  docker: <DockerIcon />,
  fastify: <FastifyIcon />,
  figma: <FigmaIcon />,
  flask: <FlaskIcon />,
  flutter: <FlutterIcon />,
  fullstack: <Layers />,
  git: <GitIcon />,
  gitea: <GiteaIcon />,
  githubactions: <GithubActionsIcon />,
  github: <GitHubIcon />,
  golang: <GoIcon />,
  javascript: <JavascriptIcon />,
  linkedin: <LinkedInIcon />,
  nextjs: <NextIcon />,
  nodejs: <NodeJSIcon />,
  prisma: <PrismaIcon />,
  python: <PythonIcon />,
  react: <ReactIcon />,
  reactnative: <ReactIcon />,
  tailwind: <TailwindIcon />,
  traefik: <TraefikIcon />,
  typescript: <TypescriptIcon />,
  vite: <ViteIcon />,
  whatsapp: <WhatsAppIcon />,
  zod: <ZodIcon />,
}
